app:
  pokemon:
    max_limit_external: 1350
spring:
  application:
    name: poke-api
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop